import { Sport } from '../model/dailyExercise'

export const SportData: Sport[] = [
  {
    name: 'Dancing',
    icon: $r('app.media.dance'),
    consume: 300, // 中等强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Bicycle',
    icon: $r('app.media.bicycle'),
    consume: 400, // 平稳骑行
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Jogging',
    icon: $r('app.media.running'),
    consume: 500, // 慢跑
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Swimming',
    icon: $r('app.media.swimming'),
    consume: 600, // 中速游泳
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Skipping Rope',
    icon: $r('app.media.skipping_rope'),
    consume: 700, // 高强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Football',
    icon: $r('app.media.football'),
    consume: 500, // 高强度间歇
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Basketball',
    icon: $r('app.media.basketball'),
    consume: 450, // 中高强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Badminton',
    icon: $r('app.media.badminton'),
    consume: 400, // 中等强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Skiing',
    icon: $r('app.media.ski'),
    consume: 500, // 中高强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Pilates Ball',
    icon: $r('app.media.pilates_ball'),
    consume: 200, // 低强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Tai Chi',
    icon: $r('app.media.tai_chi'),
    consume: 180, // 低强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Shuttlecock',
    icon: $r('app.media.shuttlecock'),
    consume: 300, // 中等强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Aerobics',
    icon: $r('app.media.Aerobics'),
    consume: 400, // 中高强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  },
  {
    name: 'Volleyball',
    icon: $r('app.media.volleyball'),
    consume: 300, // 中等强度
    unit: 'hour',
    isStart: false,
    burnedCalories: 0,
    usedTime: 0
  }
];
